name: Update pnpm lockfile on Renovate PRs

on:
  pull_request:
    branches:
      - 'renovate/**'
    paths:
      - pnpm-workspace.yaml
    paths-ignore:
      - pnpm-lock.yaml

jobs:
  update-pnpm-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
          node-version-file: package.json

      - name: Install pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Update pnpm lockfile
        run: pnpm update --lockfile-only

      - name: Commit and push updated lockfile
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pnpm-lock.yaml
          git commit -m "chore: update pnpm lockfile"
          git push origin HEAD:${{ github.head_ref }}
